### ISSUE TITLE
Symlink creation requires elevated command prompt in Windows

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#120] opened 2017-05-03 14:23 UTC
I tried digging into this but couldn't seem to find anything. 

Backstory:

In the new [Windows 10 Creators Update](https://blogs.windows.com/windowsexperience/2017/04/11/whats-new-in-the-windows-10-creators-update/) it is mentioned that symlinks in Windows changed. Windows symlinks do not require admin rights anymore (see an entire separate article [here](https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/#8d0mcYYc12E4qvf6.97) on it).

Now what is interesting is we all know before the change that in order to make a symlink in Windows you needed an elevated command prompt but when doing so with node it was not required. (I assume that in that case since node is running with elevated privileges this is fine). But with the new update symlinks in Node do not work unless the node process is ran from an elevated command prompt. (This was observed by myself and others).

So it seems as if the Windows update changed manual symlinks but broke for the cases like Node. Maybe Node hasn't accounted for the change yet in their API? At the end of the blog posts (which was posted in December) Windows mentions that are going to work with git and Node on the new change...

> We are also working with the owners of open-source community tools such as Git and npm so they know symlink improvements are coming and can make the necessary changes to better support symlinks on Windows.

I would think that Node accounted for this change by now since it is about 5 months after the blog post, but reading the change log I didn't come across anything.

**Comment by alallier** [comment] 2017-05-16 15:02
Note: Fine in Windows Powershell

**Comment by alallier** [comment] 2017-06-08 16:57
#147 fixes the models and lib directory, are we planning to do the same fix for the symlinks in the public directory?

**Comment by kethinov** [comment] 2017-06-08 17:09
no

symlinks are needed in that case. i'm really not sure what to do about it. the win10 blog says elevated permissions shouldn't be needed but they still seem to be for some reason

**Comment by alallier** [comment] 2017-06-08 18:08
Yeah quite confusing

**Comment by kethinov** [comment] 2017-12-30 21:57
closing this since there's really not much we can do about it

**Comment by alallier** [comment] 2018-01-10 13:23
For what it's worth I just generated a new app and didn't need elevated privileges to make the symlinks.

```
Version 1709 (OS Build 16299.192)
```

**Comment by alallier** [comment] 2018-05-30 15:50
Finally figured out this pain of an issue out!

So in this [Microsoft article](In this [article](https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/)) you can clearly see that pushed out a feature for non-privileged symlink creation in Windows. But why did we not see this working on different machines and working on others. Well in the fine print you need to have [developer mode](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development) enabled. Once you do this you can start a Roosevelt app and it will write the public symlinks without an admin command prompt. So the README has to be updated to say something to the extent, if you use Windows make sure you enable developer mode or you will be forced to start the app with ad admin command prompt the first time to create symlinks

**Comment by kethinov** [comment] 2018-05-30 15:51
good info thanks, reopening to reflect that action item

**Comment by mulligan121** [comment] 2018-10-29 18:30
@alallier It should close this because we use junctions now for Windows and they don't require elevated privileges.

**Comment by kethinov** [comment] 2018-10-29 20:52
I believe so as well but we should leave the issue open until this is explicitly tested.

**Comment by kethinov** [comment] 2018-11-09 03:29
I just confirmed this is fixed in Windows.

**Closed by kethinov** 2018-11-09 03:29 UTC
Labels: bug
