### ISSUE TITLE
Add Support for Read-Only Filesystems (i.e. Docker/Kubernetes)

### ISSUE THREAD

**Issue by dishad** [rooseveltframework/roosevelt#1145] opened 2022-03-23 16:17 UTC
## Introduction/Problem Statement

Currently you cannot use roosevelt appropriately in read-only environments like Docker/Kubernetes. Every file created by roosevelt on app startup can be created ahead of time. Adding a _build_ step will allow all file writing to happen before startup. When creating a container, this new _build_ step can be run during image creation. Doing so allows container run-times like Docker and Kubernetes to start without needing to write files, which means the containers can have more secure read-only file systems.

We have done an audit of files that write on startup and we have proposed solutions to the problem statement below.

## File Audit

When taking a look at the following modules that create files, I saw that there aren't many situations where we do this so it should be fairly simple to implement a way to get around it.

[`lib/tools/fsr.js`](https://github.com/rooseveltframework/roosevelt/blob/65a9b95a07f0c7f254afb0db6a5919c08e8f3824/lib/tools/fsr.js)
- writeFileSync function - writes files
- ensureDirSync function - creates directories

[`lib/isomorphicControllersFinder.js`](https://github.com/rooseveltframework/roosevelt/blob/65a9b95a07f0c7f254afb0db6a5919c08e8f3824/lib/isomorphicControllersFinder.js)
- writeFileSync JS files

[`lib/preprocessCss.js`](https://github.com/rooseveltframework/roosevelt/blob/65a9b95a07f0c7f254afb0db6a5919c08e8f3824/lib/preprocessCss.js)
- writeFileSync CSS files
- ensureDirSync Creates CSS directories

[`lib/viewsBundler.js`](https://github.com/rooseveltframework/roosevelt/blob/65a9b95a07f0c7f254afb0db6a5919c08e8f3824/lib/viewsBundler.js)
- writeFileSync JS files

[`lib/generateSymlinks.js`](https://github.com/rooseveltframework/roosevelt/blob/65a9b95a07f0c7f254afb0db6a5919c08e8f3824/lib/generateSymlinks.js)
- ensureDirSync makes statics and public directories

[`lib/mapRoutes.js`](https://github.com/rooseveltframework/roosevelt/blob/65a9b95a07f0c7f254afb0db6a5919c08e8f3824/lib/mapRoutes.js)
- ensureDirSync makes models, views, controllers directories

If I missed any files here feel free to add to this list.

## Conclusion/Solutions

1. Add support for new config item, called build, such that roosevelt will build all items and not start any services
    * instances of roosevelt apps can write their own build scripts which will call roosevelt with this config item (and any other build steps the app requires)

2. Add support for new config item called `read-only` so that when the app starts nothing is written (build step above is required)

This allows container run-times like Docker and Kubernetes to build static files at image build time rather than app startup which allows for tighter permission settings like read-only filesystems.

**Comment by alallier** [comment] 2022-03-23 16:57
Thanks I actually forgot about that. We will still need a way to generate the folder and file structure ahead of time and not start the app so we can bake that into Dockerfiles.

**Comment by kethinov** [comment] 2022-03-24 03:31
Couldn't the build step be to just start the app once, let it generate the files that are needed, then flip that setting off all as part of a build script?

**Comment by Autre31415** [comment] 2022-03-24 15:01
You could accomplish this without starting and stopping the app by using `initServer()` rather than `startServer()`. This will build all your artifacts, then in your runtime version in docker you can disable the file generation feature.

**Comment by kethinov** [comment] 2022-07-21 15:06
This is essentially a duplicate of https://github.com/rooseveltframework/roosevelt/issues/891 which was resolved in 0.20.0.

**Closed by kethinov** 2022-07-21 15:06 UTC
Labels: discussion
